#!/bin/sh

if [ -z $1 ];then
	echo 'set args'
elif [ $1 -eq 11 ];then
	echo 'toggle DB'
	cp -p /Users/t.asamoto/Library/Mobile\ Documents/com~apple~CloudDocs/work/ftp11 /Users/t.asamoto/Library/Mobile\ Documents/com~apple~CloudDocs/work/.ftpconfig
elif [ $1 -eq 10 ];then
	echo 'toggle Front'
	cp -p /Users/t.asamoto/Library/Mobile\ Documents/com~apple~CloudDocs/work/ftp10 /Users/t.asamoto/Library/Mobile\ Documents/com~apple~CloudDocs/work/.ftpconfig
else
	echo 'set valid number'
fi
